### NOT FINISHED! ###

FROM jupyter/datascience-notebook:137a295ff71b
WORKDIR /home/jovyan

RUN curl -O https://raw.githubusercontent.com/pupster90/io_docker_setup/master/v1.0.0/1_0_0.sh
RUN chmod +x 1_0_0.sh && ./1_0_0.sh

CMD jupyter notebook





